jobs:
  - name: u16nodalltesting
    type: runSh
    steps:
      - TASK:
          runtime:
            options:
              imageName: "drydock/u16nodall"
              imageTag: master
          script:
            - grunt --version
            - mocha --versio
            - vows --version
            - casperjs --version
            - bower --version
            - phantomjs --version
            - java -jar /usr/local/selenium/selenium-server-standalone-3.11.0.jar --version
            - nodejs --version
            - npm --version
