jobs:
  - name: u16nodalltesting
    type: runSh
    steps:
      - TASK:
          runtime:
            options:
              imageName: "drydock/u16nodall"
              imageTag: master
          script:
            - grunt --version
            - mocha --version
            - vows --version
            - casperjs --version
            - bower --version
            - phantomjs --version
            - java -jar /srv/selenium-server-standalone-3.11.0.jar --version
            - node --version
            - nvm list
            - npm --version
